
name: Deploy AWS Housing Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas psycopg2-binary bandit tfsec

    - name: Run Bandit security scan
      run: bandit -r lambda_function.py

    - name: Run tfsec security scan
      run: tfsec .

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform

    - name: Terraform Plan
      run: terraform plan -var-file=terraform.tfvars
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -var-file=terraform.tfvars -auto-approve
      working-directory: terraform
    